// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ZhYopll6CLx7FUp2HTt_AlMCBwZ7cMA',
    appId: '1:951513544949:web:94593a14c79b101803edbc',
    messagingSenderId: '951513544949',
    projectId: 'chat-app-9aaa5',
    authDomain: 'chat-app-9aaa5.firebaseapp.com',
    storageBucket: 'chat-app-9aaa5.appspot.com',
    measurementId: 'G-D17SLNXD72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUV75x1DziAJxQ5XHzxPgpis7BKV4pHKU',
    appId: '1:951513544949:android:d30eb8e6551a50c003edbc',
    messagingSenderId: '951513544949',
    projectId: 'chat-app-9aaa5',
    storageBucket: 'chat-app-9aaa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYChM8sMtPv-jiSx7MYHBYbeqjYlGYh6k',
    appId: '1:951513544949:ios:f7e61aec00b82f0f03edbc',
    messagingSenderId: '951513544949',
    projectId: 'chat-app-9aaa5',
    storageBucket: 'chat-app-9aaa5.appspot.com',
    iosClientId: '951513544949-30dq2krjjlo4i1jde38t3gqfad207pda.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYChM8sMtPv-jiSx7MYHBYbeqjYlGYh6k',
    appId: '1:951513544949:ios:0d9bd51bc6055d1003edbc',
    messagingSenderId: '951513544949',
    projectId: 'chat-app-9aaa5',
    storageBucket: 'chat-app-9aaa5.appspot.com',
    iosClientId: '951513544949-hikbl5ou7jqi8tmols9bn3jldgce8dn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
